config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
  root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    render :show
  end

  def edit
  end

  def show

  end

  def update
  end

  def destroy
  end

  private
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<h1>Flat listing</h1>
<%= link_to "new flat", new_flat_path %>
<% @flats.each do |flat| %>
  <ul>
   <li><%= flat.name %> </li>
   <li><%= flat.address %> </li>
   <li><%= flat.description %> </li>
   <li><%= flat.price_per_night %> </li>
   <li><%= flat.number_of_guests %> </li>
  </ul>
<% end %>

app/views/flats/new.html.erb
<h1>New flat</h1>
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description%>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit %>
<% end %>

app/views/flats/show.html.erb
<h1>Flat show</h1>
<%= link_to "index", flats_path %>
<ul>
  <li><%= @flat.name %> </li>
  <li><%= @flat.address %> </li>
  <li><%= @flat.description %> </li>
  <li><%= @flat.price_per_night %> </li>
  <li><%= @flat.number_of_guests %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>